/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [4:0] io_led,
    output reg spi_miso,
    output reg [3:0] spi_channel,
    output reg avr_rx,
    output reg a,
    output reg b,
    output reg c,
    input sum,
    input carry,
    input [2:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led[0+0-:1] = io_dip[0+0-:1];
    io_led[1+0-:1] = io_dip[1+0-:1];
    io_led[2+0-:1] = io_dip[2+0-:1];
    a = io_dip[0+0-:1];
    b = io_dip[1+0-:1];
    c = io_dip[2+0-:1];
    io_led[3+0-:1] = sum;
    io_led[4+0-:1] = carry;
  end
endmodule
